example.property: "I AM A PROD PROPERTY OVERRIDE in production"
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/usercenter?setUnicode=true&characterEncoding=utf8
    username: xiaodong
    password: time4@FUN
    driver-class-name: com.mysql.cj.jdbc.Driver